global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # Laravel (tournera en local sur ton Mac)
  - job_name: 'laravel'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'

  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
